### ISSUE TITLE
component name is confusing

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/dictionary-component#3]
The first reaction seeing this component name is, wow great now I can look into a dictionary to find definitions of some words I don't understand. The icon is almost identical to the dictionary icon on MacOSX.

Only after checking the component and reading the README I realise this is the lookup-tables feature made into the component. What it does is very useful, however, the name is really confusing.

I suggest renaming the component into `lookup-table component` to better reflect the functionality.

**Comment by zubairov** [comment]
@juhrmacher I share the concerns of the @khanzadyan here and to be honest this component could be a workaround before the proper usable implementation of `Lookup Tables` product feature is implemented. 

I believe next steps here should be that @drobiazko and @juhrmacher discuss the plan on how this workaround component can be used / introduced and what should be the actions on deprecated / rollback the use of this component after a proper `Lookup Table`, which is a standard feature of integration platforms / ETL tools, become available.

**Comment by juhrmacher** [comment]
I‘m fine with renaming the component to lookup-table component

**Comment by kirill-levitskiy** [comment]
Renamed
