### ISSUE TITLE
Values does not have to be unique

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/dictionary-component#33]
# Other Feature Request

## Description

Currently, all the elements must be unique. An error will be thrown otherwise. However there may be many cases when duplicates are allowed. As for me - even more than vice versa.

## Definition of Done

Consider the following table:
```
npe01__Payment_Method__c,Customer(entity_internalId)
Credit Card,315
FOHK Charities,314
Givo - Stripe,317
Stripe,317
Credit Card – AMEX,316
Credit Card – Master Card,315
Credit Card – VISA,315
```

I want any of `Credit Card`, `Credit Card – Master Card`, `Credit Card – VISA` to result in the same `15` value. 
A think at least single-direction  duplicates should be allowed.

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/dictionary-component/releases/tag/1.2.0
