### ISSUE TITLE
Rename configuration fields in Lookup from table action

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/dictionary-component#5]
**Description:**
Currently action `Lookup from table` has config fields with incorrect names, the should be renamed:
`From this table` -> `From this column`
`To this table` -> `To this column`

![image](https://user-images.githubusercontent.com/36419533/71244788-f9c8d880-231b-11ea-8608-a2d1747d482e.png)

Where to rename:

- component.json
- Readme.md

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/dictionary-component/releases/tag/1.2.0
