### ISSUE TITLE
Problem with validation if empty line in the end of a file

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/dictionary-component#7]
The validation credentials step fails if there is an empty row in the end of a file.

AR:
The component throws an exception without any details about the cause of the issue. The file logs don't have any information about a problem.

ER:
The component should trim empty lines in the end of the file before validation.

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/dictionary-component/releases/tag/1.2.0
